name: scheda_dnd_5e
description: "\"Scheda D&D 5e\" è un’applicazione che consente a tutti i giocatori di Dungeons & Dragons di gestire i propri personaggi e le proprie campagne. Grazie alla nostra app si potranno creare e gestire i personaggi e le campagne condividendole con i propri gruppi di amici!"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.18.0
  firebase_storage: ^11.6.11
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.6.22
  google_sign_in: ^6.2.1
  tuple: ^2.0.2
  expand_tap_area: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/images/dice/
      - assets/images/
      - assets/images/icons/
      - assets/images/icons/png/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
