// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBzJTcnhg2nVvr2MX2vTUDS_kyInJBE1o',
    appId: '1:245540512812:android:db0e8d6ab544c919e21d89',
    messagingSenderId: '245540512812',
    projectId: 'scheda-dnd',
    storageBucket: 'scheda-dnd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIIkCptTXAUx7xdtk12f0_-vCOOSz3Wic',
    appId: '1:245540512812:ios:60f8c3d978f00f83e21d89',
    messagingSenderId: '245540512812',
    projectId: 'scheda-dnd',
    storageBucket: 'scheda-dnd.appspot.com',
    androidClientId: '245540512812-vk2ous5pkam1ac1dionl1rifvpvtbkt3.apps.googleusercontent.com',
    iosClientId: '245540512812-38m2d7ajbo8itr398rnld4gasqnbjb72.apps.googleusercontent.com',
    iosBundleId: 'it.dnd.schedaDnd5e',
  );
}
